# mc server ip
hostname: localhost
# mc server port
port: 25569
# ayungee port
web_port: 25565
# if this is behind a reverse proxy, such as caddy or nginx. uses X-Real-IP header.
forwarded: false
# forward eagler-specific packets?
eag_packets: false
# origin blacklist URL (leave empty to disable syncing)
origin_blacklist: "https://g.eags.us/eaglercraft/origin_blacklist.txt"
# whitelisted origins -- if specified, only allows the listed origins to connect
# for example,
#   - "https://g.eags.us"
origins: []
# motd info
motd:
  # the motd itself
  lines:
    - "Welcome to my"
    - "ayungee-powered server!"
  # max players (purely visual)
  max: 20
  # online players (purely visual)
  online: 4
  # name of server
  name: An ayungee-powered Eaglercraft server
  # players online (purely visual)
  players:
    - "whar?"