# mc servers in network. first one is default/hub
servers:
  - localhost:25569
# ayungee port
web_port: 25565
# if this is behind a reverse proxy, such as caddy or nginx. uses X-Real-IP header.
forwarded: false
# origin blacklist URL (leave empty to disable syncing)
origin_blacklist: "https://g.eags.us/eaglercraft/origin_blacklist.txt"
# whitelisted origins -- if specified, only allows the listed origins to connect
# for example,
#   - "https://g.eags.us"
origins: []
# enable /server command?
server_cmd: true
# authentication info
auth:
  # use auth
  enabled: false
  # max registers per ip (set to 0 for unlimited, not recommended, but necessary for servers that cannot see user IPs)
  ip_limit: 0
# motd info
motd:
  # the motd itself
  lines:
    - "Welcome to my"
    - "ayungee-powered server!"
  # max players (purely visual)
  max: 20
  # online players (purely visual)
  online: 4
  # name of server
  name: An ayungee-powered Eaglercraft server
  # players online (purely visual)
  players:
    - "whar?"